### ISSUE TITLE
Watchlist from Robinhood App

### ISSUE THREAD

**Issue by Goldeneye22** [Jamonek/Robinhood#100]
I have a watchlist stored in my Robinhood account. Does anyone know a way to extract that watchlist from my account to be used like securities_owned?

**Comment by badubies** [comment]
I figured it out!
The endpoint is already listed. Just add this function to the Robinhood class. I put it between positions and securities owned.
`    def watchlists(self):
        return self.session.get(endpoints.watchlists() + 'Default/', timeout=15).json()`

**Comment by Goldeneye22** [comment]
Wow! Thank you badubies, I was missing the 'Default' part on my side, so I kept getting a blank watchlist back. You rock thank you again!
