### ISSUE TITLE
How to pull stock names/tickers from order history

### ISSUE THREAD

**Issue by aamazie** [Jamonek/Robinhood#103]
There doesn't seem to be a way to find what the stock name or the ticker of the stock was that was ordered in the order history. Any guidance or suggestions would be extremely appreciated.

I would recommend adding this to the endpoints if possible for ease of use.

**Comment by ketozhang** [comment]
Agreed, why is this issue closed?

`Robinhood.securities_owned` and `Robinhood.order_history` contains no information on what ticker symbol each transaction is. I find no use of order history without it.

**Comment by ketozhang** [comment]
I have yet contributed or looked much into the implementation of this framework. I will assume for now the general rule is **don't touch the original API JSON output**.

The way to output order history ticket symbol is quite simple:

```python
from Robinhood import Robinhood

my_trader = Robinhood()
logged_in = my_trader.login(username="USERNAME HERE", password="PASSWORD HERE")

# Get order history as usual
order_history = my_trader.order_history()['results']

# Append ticker symbol to order history
symbols = [my_trader.session.get(order['instrument']).json()['symbol'] for order in order_history]
for order, symbol in zip(order_history, symbols):
    order['symbol'] = symbol
```

Now my question is does this Robinhood framework allows attributes of cleaned up data to be in a Robinhood instance?

**Comment by aamazie** [comment]
@ketozhang try looping into the stock instruments in the order history.
