### ISSUE TITLE
Options Data

### ISSUE THREAD

**Issue by tgikal** [Jamonek/Robinhood#105]
I've tried to use the get_options function every way I can think of based on the what I see in the source.
trader.get_options('SODA', '2018-06-22', 'call') returns error
trader.get_options('SODA', ['2018-06-22'], 'call') returns error
What is the correct way to use this function?

**Comment by tgikal** [comment]
I'm lost... I poked around in it a bit and separated the ["id"] key from the quote_data section, then it was working properly, but it's still working after I put it back the way it was, maybe the server was down.
-> trader.get_options('SODA', '2018-06-22', 'call') works now

**Comment by jasonleehodges** [comment]
Were you logged in via the login_prompt() or other method the first time you tried to call it? What was the error message that you got?

**Comment by tgikal** [comment]
logged in via the .login(username = , password = )
using the .instruments("STOCK") function worked, but when I tried trader.get_options('SODA', '2018-06-22', 'call') I got an error saying ["id"] was not a valid key.
I broke it apart and found the quote_data was returning nothing, but after running my test script about 3 times, logging in each time, it started working.
