### ISSUE TITLE
How to check minimum required price increments

### ISSUE THREAD

**Issue by badubies** [Jamonek/Robinhood#113]
I was writing a program that automatically creates limit sell orders for all my positions. For some of the stocks, I'd get a 400 HTTP error. I tried submitting the failed orders on Robinhood, and it gave a minimum price increment error, then allowed me to round my price to the nearest 5 cents. How could I check this beforehand on the API, or make the rounding change. 
![image](https://user-images.githubusercontent.com/40771217/42177756-cac455d0-7de2-11e8-8391-024cef25ee31.png)

**Comment by jasonleehodges** [comment]
If you hit the instrument endpoint for that particular instrument it looks like there is a `min_tick_size` property that shows "0.0500" as it's value. If you check the same property for a stock like AAPL the `min_tick_size` is null. So I think if you check that property first that should give you what you need.
