### ISSUE TITLE
Add options functionality

### ISSUE THREAD

**Issue by westonplatter** [Jamonek/Robinhood#123]
I think it would be helpful to add the (stock) options commands.

In particular, 
- [ ] get options order history
- [ ] place 1 leg option orders
- [ ] place multi-leg option orders

**Comment by prjwlk** [comment]
Hi, is there any update on the multi- leg option order functionality, can someone give me unofficial format of the code to try it out...

**Comment by westonplatter** [comment]
glad you asked, @prjwlk. I won't be working to add option order functionality to this repo. 

I created my own RH client, https://github.com/westonplatter/fast_arrow, and am almost finished with implementing 1/2/multi leg option orders. See this issue for more details, https://github.com/westonplatter/fast_arrow/issues/10.

**Comment by westonplatter** [comment]
@prjwlk added basic option ordering ability to `fast_arrow`. See this PR, https://github.com/westonplatter/fast_arrow/pull/34.
