### ISSUE TITLE
get_options_data 404

### ISSUE THREAD

**Issue by edPratt** [Jamonek/Robinhood#141]
Trying to get some example output for this aapl option: pprint(my_trader.get_option_market_data('ce6822ae-67fa-4855-8642-ea3b257e5505'))

Error below:
equests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.robinhood.com/oauth2/migrate_token/

Anyone know how to figure out the new url if RH has changed it for options data?

**Comment by avidbrandy** [comment]
Use the following example format:

print(my_trader.get_options('MSFT', '2019-03-29', 'call'))

**Comment by DSLituiev** [comment]
This returns
```
ValueError: Appending path '/' starting from slash is forbidden
```

**Comment by DSLituiev** [comment]
After fixing the trailing slash, this pops up:
```
---------------------------------------------------------------------------AttributeError Traceback (most recent call last)<ipython-input-4-4eee4f38c522> in <module>----> 1 rh.get_options('MSFT', '2019-03-29', 'call')/home/anaconda3/envs/fin/lib/python3.7/site-packages/pyrh/robinhood.py in get_options(self, stock, expiration_dates, option_type) 500 contract 501 for contract in self.get_url(--> 502 urls.options(chain_id, _expiration_dates_string, option_type) 503 )["results"] 504 ]AttributeError: module 'pyrh.urls' has no attribute 'options'
```
When I fix this : `options` -> `build_options`, it returns an empty list
