### ISSUE TITLE
Order Placing/Submitting Isn't Working

### ISSUE THREAD

**Issue by aamazie** [Jamonek/Robinhood#152]
I'm still having issues placing orders. Suddenly today, after I have officially gained my withdrawable cash and not just buying power, none of my buy functions are working. I am getting this error:

    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/orders/

Any suggestions? I updated my code for these functions, but they were working and I don't think my updates are what is causing this.

**Comment by aamazie** [comment]
I figured it out. Problem was with Robinhood updating to Clearing by Robinhood, not on the API's end. Had to update the app and agree to their new service in order to place any orders. Pain in the ass to try to figure that out. At least I know the API is good now... For now...

**Comment by aamazie** [comment]
I figured it out. Problem was with Robinhood updating to Clearing by Robinhood, not on the API's end. Had to update the app and agree to their new service in order to place any orders. Pain in the ass to try to figure that out. At least I know the API is good now... For now...

**Comment by 7ynk3r** [comment]
to accept the new terms update the app.
