### ISSUE TITLE
InvalidTickerSymbol

### ISSUE THREAD

**Issue by GoldenEye22** [Jamonek/Robinhood#165]
Is anyone randomly getting this issue? My code will run for fine then this error will occur. The tickers were valid last week and are still valid on the Robinhood app.

**Comment by GregP83** [comment]
Have the same issue that happens in:
 def quote_data(self, stock=''):

I keep getting
 requests.exceptions.HTTPError:

I didn't update any code so it must be change in RH servers.

**Comment by GoldenEye22** [comment]
Yes, I see it in quote_data and fundamentals. Definitely seems to be an issue with RH. Glad I am not the only one seeing this!

**Comment by GregP83** [comment]
Yep: even in web browser https://api.robinhood.com/quotes/UGAZ/ will sometimes show json and sometimes Error 401. 
In my code I added while(True) loop with retry and 1 sec sleep on the HTTPError exception.

**Comment by GoldenEye22** [comment]
Robinhood API Issue

**Comment by trevorwelch** [comment]
@GoldenEye22 I'm pretty sure they're shutting down that endpoint. This page is blank all the time now: https://api.robinhood.com/quotes/AAPL/ ... did you find another one?

**Comment by GoldenEye22** [comment]
Yes, it sure seems that way. This is disappointing since I use a lot of data from my account in my code. Hopefully they are just updating hardware and will bring it up again eventually.

**Comment by trevorwelch** [comment]
> Yes, it sure seems that way. This is disappointing since I use a lot of data from my account in my code. Hopefully they are just updating hardware and will bring it up again eventually.

Pass your auth token with your quotes GET request and it works :)

**Comment by jstuart3** [comment]
> > Yes, it sure seems that way. This is disappointing since I use a lot of data from my account in my code. Hopefully they are just updating hardware and will bring it up again eventually.
> 
> Pass your auth token with your quotes GET request and it works :)

@trevorwelch can you clarify? How do I access my auth token? Is your advice language specific? I'm working in Python.

**Comment by GoldenEye22** [comment]
@jstuart3 Please see #167 where it is described in detail.
