### ISSUE TITLE
inconsistent result on volume

### ISSUE THREAD

**Issue by indigo62018** [Jamonek/Robinhood#171]
Hi,

I'm not sure which forum or mail list I should discuss this topic. But, I'm guessing everybody here is familiar with this.

When I fetch volume data continuously from endpoint https://api.robinhood.com/fundamentals , I found the volume decreases sometimes. It usually increases as time goes as expected. But, sometimes, decreasing happens - with 5% reproducibility.

For example,
MSFT : updateat 2019-03-27T13:30:01Z | volume: 180605.000000
MSFT : updateat 2019-03-27T13:30:21Z | volume: 832565.000000
MSFT : updateat 2019-03-27T13:30:41Z | volume: 1259314.000000
MSFT : updateat 2019-03-27T13:31:01Z | volume: 421252.000000 // What???
MSFT : updateat 2019-03-27T13:31:21Z | volume: 1332935.000000
MSFT : updateat 2019-03-27T13:31:41Z | volume: 521442.000000 // What???

I also posted this on below but couldn't get answer.

https://www.reddit.com/r/algotrading/comments/b6fmbi/weird_decreasing_volume_sequence_data_fetched/

My feeling is, looks there's multiple API server on RH and they aren't sync correctly, timely.

Does anybody have same issue with me?

**Comment by ai2283** [comment]
Just a note, I use robinhood mobile app daily and I consistently observe
this issue in their app. I suggest you reach out to them directly or post
on robinhood reddit page.

**Comment by Jamonek** [comment]
Reaching out to Robinhood may result in your account being shutdown for using an unofficial API. I’d be careful 

Best,

Jamone

**Comment by indigo62018** [comment]
thanks guys for your advice. :) let me close this
