### ISSUE TITLE
Did Robinhood change something? 

### ISSUE THREAD

**Issue by tc0nn** [Jamonek/Robinhood#203]
I can't login. Using the same script that worked a week ago. Saw an update to this repo so I pulled that in but made no difference. Keep getting:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Robinhood/Robinhood.py", line 116, in login
    res.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tconnolly/repos/tims-robinhood-bot/app/runme.py", line 68, in <module>
    my_trader.login(username,password)
  File "/usr/local/lib/python3.7/site-packages/Robinhood/Robinhood.py", line 119, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed`

I've turned off MFA and changed my password. Website lets me login just fine...

**Comment by tc0nn** [comment]
I'm guessing by the level of response this question has received, nobody else is having issues.

**Comment by Outlaw782** [comment]
@tc0nn I am having the same issue. I added to another thread. I didn't receive a response either. 

@Jamonek any idea what might be going on?

**Comment by Jamonek** [comment]
I'm looking into the issue.

**Comment by Outlaw782** [comment]
Thanks @Jamonek  for the quick reply.

**Comment by stoooops** [comment]
I am also facing this issue.

```
>>> logged_in = Robinhood().login("username", "password")
Traceback (most recent call last):
  File "/home/cory/.pyenv/versions/finapp/lib/python3.8/site-packages/Robinhood/Robinhood.py", line 116, in login
    res.raise_for_status()
  File "/home/cory/.pyenv/versions/finapp/lib/python3.8/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cory/.pyenv/versions/finapp/lib/python3.8/site-packages/Robinhood/Robinhood.py", line 119, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed
```

**Comment by GoldenEye22** [comment]
I have not updated in a while and I was having no issues as of Friday. Have any of you tried reverting commits until it functions again? Then you can help trace the issue to a certain change.

**Comment by GoldenEye22** [comment]
I setup seems to work with MFA. I haven't updated from Github is months. I do notice that after 30 - 40 minutes Robinhood is logging me out. Therefore I need to login again to access the API.

**Comment by GoldenEye22** [comment]
I do this:
`working = False
        while not working:
            try:
                rp.rhma.market_analysis(trader,tick_notify,loss_trig,gain_trig,max_value)
                working = True
            except:
                print ('Failed to do Market Analysis')
                try:
                    time.sleep(ref_time)
                    trader = Robinhood()
                    trader.login(username=loginstr[0],password=loginstr[1],qr_code=loginstr[2])
                    print ('Login')
                except:
                    print ('Cant Login')
                    time.sleep(ref_time)
                    pass
                pass              `

**Comment by GoldenEye22** [comment]
@tc0nn @stoooops We have needed MFA for months not sure how you were getting around without using it.

**Comment by dirtyhatch** [comment]
I too am receiving the initial problem

**Comment by GoldenEye22** [comment]
Robinhood servers have been down all morning possibly all weekend. Big screw up on their part it seems.

**Comment by GoldenEye22** [comment]
https://www.cnbc.com/2020/03/02/robinhood-says-its-experiencing-a-system-wide-outage-as-markets-rebound-in-heavy-volume-monday.html

**Comment by Outlaw782** [comment]
@GoldenEye22  Thanks for the update.

Would you care to provide a quick example of how use MFA? I didn't see an example in the docs anywhere. Do I just go into Robinhood.py and type in the code that's text to me?

**Comment by GoldenEye22** [comment]
README.md

**Comment by GoldenEye22** [comment]
@Jamonek I don't think you ever pulled @aamazie Readme

[README.md](https://github.com/aamazie/Robinhood/blob/master/README.md)

@aamazie implemented MFA last year.

**Comment by GoldenEye22** [comment]
#150 probably because it was never resolved

**Comment by GoldenEye22** [comment]
to be honest I forked from [Robinhood](https://github.com/aamazie/Robinhood) back when Robinhood update occurred.

**Comment by Outlaw782** [comment]
@GoldenEye22 I did not realize MFA was a requirement. That is probably the issue I am having then.

I'll try and work on this tomorrow. Thanks so much for the info and quick responses.

**Comment by Jamonek** [comment]
I’ll pull in the updated README now. Also this is a separate topic but is anyone open to maintaining this project? I’ve been busy with other projects and personal life.

**Comment by tc0nn** [comment]
> @tc0nn @stoooops We have needed MFA for months not sure how you were getting around without using it.

Didn't say I was getting around without, but I turned it off to see if that made any difference. It didn't.

**Comment by tc0nn** [comment]
> I’ll pull in the updated README now. Also this is a separate topic but is anyone open to maintaining this project? I’ve been busy with other projects and personal life.

I could help out. A friend and I were about to base a new project off this repo.

**Comment by GoldenEye22** [comment]
@tc0nn try it now with MFA, mine is working now that the Robinhood servers are back up.

**Comment by tc0nn** [comment]
> @tc0nn try it now with MFA, mine is working now that the Robinhood servers are back up.

Same:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Robinhood/Robinhood.py", line 116, in login
    res.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runme.py", line 68, in <module>
    my_trader.login(username,password)
  File "/usr/local/lib/python3.7/site-packages/Robinhood/Robinhood.py", line 123, in login
    return self.login(username,password,mfa_code)
  File "/usr/local/lib/python3.7/site-packages/Robinhood/Robinhood.py", line 119, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed

I'm going to add some ridiculously verbose messages to it and see what I get.

**Comment by tc0nn** [comment]
Works now

**Comment by tc0nn** [comment]
Maybe the "hard reboot" of Robinhood.com today did the trick. Or they reverted something on their end.

**Comment by Outlaw782** [comment]
@GoldenEye22 Thanks so much for your help again, just pulled the repo you linked, set MFA and my QR code and I'm good to go now.
