### ISSUE TITLE
Buying/Selling shares causes Bad Request Error

### ISSUE THREAD

**Issue by jsmwoolf** [Jamonek/Robinhood#25]
Whenever the user tries to buy/sell a share, they get a Bad Request Error from the server.

**Comment by jsmwoolf** [comment]
Should have referred to using requests.json() to figure out the reason message.

**Comment by shomran** [comment]
@jsmwoolf  how  did you solve this issue?  when I get requests.json() , I end up with:
{'side': ['This field is required.'], 'quantity': ['This field is required.'], 'time_in_force': ['This field is required.'], 'account': ['This field is required.'], 'symbol': ['This field is required.'], 'instrument': ['This field is required.'], 'type': ['This field is required.'], 'trigger': ['This field is required.']}
