### ISSUE TITLE
Finish TODOs in `Robinhood.py`

### ISSUE THREAD

**Issue by dsouzarc** [Jamonek/Robinhood#47]
Add the custom `exceptions` marked as `TODO`s in `Robinhood.py`

**Comment by dsouzarc** [comment]
See

https://github.com/Jamonek/Robinhood/pull/49

**Comment by Jamonek** [comment]
I'll have a look or if anyone else wants to go ahead. My time has been taken up with work and my business lately. Will definitely make more time for this project so that it may continue to thrive.

**Comment by dsouzarc** [comment]
@Jamonek no worries - I actually just implemented it (see the PR). I actually worked on an early version of this with Rohan Pai a few years ago when he first wrote the article

**Comment by Jamonek** [comment]
Thank you for your hard work @dsouzarc! Very thankful to you and Rohan
