### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden LoginFailed

### ISSUE THREAD

**Issue by aceidon** [Jamonek/Robinhood#56]
Login trader appears to be broken?
Did Robinhood change something?

Traceback
 (most recent call last):
  File "C:\Python3\lib\site-packages\Robinhood\Robinhood.py", line 124, in login
    res.raise_for_status()
  File "C:\Python3\lib\site-packages\requests\models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.robinhood.com/api-token-auth/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\Robinhood\Robinhood.py", line 128, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed

**Comment by ciresnave** [comment]
I just verified it is working fine for me.  Perhaps there is an issue in your code?  If you'd like to post it I would be happy to take a look and tell you if I see an issue.

**Comment by aceidon** [comment]
Sorry for the delay.  I'm still having problems.  Here is my code:

This still kicks up the 403 error.  (Obviously the my_username and my_password are changed.  I have checked to make sure that they are both correct.)  I can still login to my mobile app manually but I can't seem to get my code to connect anymore.

```
from Robinhood import Robinhood
from time import sleep

my_trader = Robinhood()
user = 'my_username'
pw = 'my_password'
i = 0
while i < 3:
    try:
        my_trader.login(username=user, password=pw)
    except Exception as e:
        print(e)
        print('Waiting 60 seconds and then retrying...')
        sleep(60)
        i += 1
print(my_trader.securities_owned())
my_trader.logout()
```

**Comment by jasonleehodges** [comment]
@aceidon is this still an issue?

**Comment by jasonleehodges** [comment]
@aceidon can you access the login endpoint from postman or by using curl from the command line?

**Comment by aceidon** [comment]
@jasonleehodges Yep, I receive the endpoints...

Changed my code to:
`my_trader = Robinhood()
user='my_username'
pw='my_password'
my_trader.login(username=user, password=pw)
print(my_trader.securities_owned())
my_trader.logout()`

And now it works just fine...  Still not entirely sure what I was doing wrong there.  I kept getting the 403 for the longest time and sort of just threw up the white flag and left my comment up here hoping against hope.

**Comment by jasonleehodges** [comment]
Excellent, glad you were able to get it working.
