### ISSUE TITLE
Request Limit

### ISSUE THREAD

**Issue by aseylys** [Jamonek/Robinhood#57]
This isn't an issue really, well, hopefully not yet. Is there a request limit to the Robinhood API? 

If I call `trader.quote_data('AAPL')` every couple seconds all day, will I eventually get rejected?

**Comment by ciresnave** [comment]
The only way to know is to try.  If you test this and get rejected or blocked please let the rest of us know.

**Comment by bdowling** [comment]
I suspect there is or will be limitations in the API at some point, it is not sustainable or reasonable for us to expect them to keep this wide open.  As more of us use it regularly I would expect to see some limits hit.  We should be reasonable in our queries and not overburden their services if we are using this.  Do you really need second-level granularity?  Make the best choices for your use cases, but in many cases you don't need to sample that much and may even be hurting your algorithms if you are.

Back in the early days of the Internet this was called being a good netizen, respect the resources of the 'net.

**Comment by aceidon** [comment]
I keep getting a 403 error and the code I had in my other issue that I opened was working perfectly fine.  I didn't start getting the 403 until after I was doing some higher testing to retrieve data on the frequency of once per 2 minutes.  Now I'm not sure if Robinhood has blocked me or what; based on what @ciresnave had stated in the other post, I suspect I might have been blocked somehow.  I can still log in on the site and through my phone; but I can't do anything through the code anymore.

**Comment by TomFaulkner** [comment]
@aceidon Any update on that? Are you able to connect now?

When calling any APIs, as @bdowling said, it is good to be the best netizen you can, use local caching and memoization to avoid unnecessary requests (also speeds things up considerably) where possible. And, given that Robinhood hasn't published or documented this API to my knowledge, I would suggest being on our best behavior with it.

**Comment by aceidon** [comment]
@TomFaulkner  No update.  I have a script that tests the login for my account and it still gets a 403.  I suspect I am still blocked.  I tested from multiple IP's so I do believe it is account level.  Maybe when the web API comes out they'll unblock me <crosses fingers>.  In the meantime, I may create a new account and test again, but it's a lot of hassle I didn't want to do so have been waiting on Robinhood and suffering through Etrade.

**Comment by jasonleehodges** [comment]
@aseylys we’re you able to test for API limits? If so, what were the results? Obviously there is no officially posted limits as Robinhood’s API is unofficial.

**Comment by aseylys** [comment]
@jasonleehodges, I actually was able to test the API, quiet extensively.

My App basically makes 2 calls per ticker symbol. One for the quote and one for the instrument. I then put it on an update of what I figured Robinhood's update time is (~3 seconds). I've run that for 25 tickets for an entire day without any issue.

I figure if you mimic behavior of the RH app well enough they don't mind the calls. But if you're updating every second for multiple tickets you'll probably run into an issue. Nobody should have to update every second anyways, that's just over kill.

**Comment by jasonleehodges** [comment]
Wow, cool - thanks for sharing @aseylys!

**Comment by jasonleehodges** [comment]
> I used the robinhood API to call every minute hoping it would run all day. Started at 616am and got stopped at 804am.

How many and what kind of calls were you making every minute?

**Comment by PIE35** [comment]
@jasonleehodges  1 company. Pulling last_trade_price.

**Comment by PIE35** [comment]
I'm going to run it again tomorrow and see what happens.

**Comment by aseylys** [comment]
Were you using any headers or proxies in your request? 

RH is pretty tight on headless requests.

**Comment by PIE35** [comment]
Embarrassed to say, but I was most likely not using a header because I don't know what you mean by a headless request.

**Comment by aseylys** [comment]
This is what I put in front of my requests, it's the same one that's being used in this library.
```
from six.moves.urllib.request import getproxies
headers = {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "en;q=1, fr;q=0.9, de;q=0.8, ja;q=0.7, nl;q=0.6, it;q=0.5",
    "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
    "X-Robinhood-API-Version": "1.0.0",
    "Connection": "keep-alive",
    "User-Agent": "Robinhood/823 (iPhone; iOS 7.1.2; Scale/2.00)"
}
proxies = getproxies()

resp = requests.get(
    url,
    data = payload,
    headers = headers,
    proxies = proxies
).json()
```

**Comment by PIE35** [comment]
@aseylys Thank you so much. 
I'm going to try to get that working tonight.

**Comment by PIE35** [comment]
Thank you again for you help. I'm gonna try it again today and see how it works.

**Comment by PIE35** [comment]
IT WORKED. You da best.

**Comment by maccers** [comment]
I ran a test, and it seems it will cut you off after you request order history more than 60 times in a minute. Anything other Robinhood requests you want me to check?

**Comment by jeremy-rutman** [comment]
any more info on rate limits? I've been ok pulling book data once a minute for one symbol, am now wanting to do several tickers
