### ISSUE TITLE
View current positions

### ISSUE THREAD

**Issue by flare9x** [Jamonek/Robinhood#67]
Hi

Is there a way to view current positions? I see nothing in example.py.

I need to check if I hold a position for my trading logic. 

Thanks

**Comment by webowl** [comment]
positions = securities_owned()['results']

Sent from my iPhone

On Jan 12, 2018, at 9:28 AM, Andrew Bannerman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

Is there a way to view current positions? I see nothing in example.py.

I need to check if I hold a position for my trading logic.

Thanks

**Comment by flare9x** [comment]
Traceback (most recent call last):
  File
"C:/Robinhood/Robinhood-master/Robinhood-master/Robinhood/buy_vxx.py", line
22, in <module>
    positions = securities_owned()['results']
NameError: name 'securities_owned' is not defined

Process finished with exit code 1

**Comment by chhatch** [comment]
Try this..

from Robinhood import Robinhood

my_trader = Robinhood()
my_trader.login(username="username", password="password")
positions = my_trader.securities_owned()['results']
