### ISSUE TITLE
instruments function trying to capitalize a string

### ISSUE THREAD

**Issue by runningChristopher** [Jamonek/Robinhood#74]
instruments = robinhood.instruments(symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Robinhood-1.0.1-py3.6.egg/Robinhood/Robinhood.py", line 193, in instruments
AttributeError: 'float' object has no attribute 'upper'

The instruments function uses a float, but supposed to use a string? Not sure where I'm getting mixed up here.

**Comment by AustinScola** [comment]
I think the instruments function takes a string as input:
`def instruments(self, stock):
        """Fetch instruments endpoint
            Args:
                stock (str): stock ticker`

**Comment by runningChristopher** [comment]
Yeah, you're right. I found my own bug in my code. I was trying to pass in a float and not a string.
Thanks for your help!
