### ISSUE TITLE
Symbol - ID Mismatch

### ISSUE THREAD

**Issue by vargasa** [Jamonek/Robinhood#76]
Hi Everyone,

Regarding a comment I did before:

https://github.com/Jamonek/Robinhood/blob/8c7b72617f945406aa43a49a960ddc21f47bf36b/Robinhood/Robinhood.py#L1211

I think this is not safe. for instance: if I want to buy "AAP", I'll end up buying "AAPL":

Trader.instruments("AAP")[0] #returns AAPL Info
Trader.instruments("AAP")[1] #returns AAP Info

We should compare symbol before placing order, the safest way would be by id. That would require a good matching symbol/id function.

**Comment by ciresnave** [comment]
I still agree. My day job has kept me busy enough that I haven't had time to write a fix for it. I'll try to get one done soon but no idea when. You could write it and help us all out.

**Comment by Jamonek** [comment]
Same here. But I’ll have everything fixed ASAP

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasonleehodges** [comment]
Here's a way that I have pulled an instrument id from a ticker that seems to be pretty safe. It takes an extra api call but it should work.

`self.get_url(self.quote_data(stock)["instrument"])["id"]`

And in your case if you were just looking for the instrument url you could just remove the id selector from the end of that expression.
