### ISSUE TITLE
Add Timeouts to Requests Calls

### ISSUE THREAD

**Issue by Miserlou** [Jamonek/Robinhood#78]
The python-requests library has a really nasty problem of not setting a default timeout value (related: https://github.com/requests/requests/issues/3070)

Therefore, sometimes random requests get "stuck" (especially with SSL connections), which is problematic for very long-running applications. This library is vulnerable to this problem because it doesn't use a default timeout.

We should add one! I can PR if you accept the idea.

**Comment by Jamonek** [comment]
Fixed in #80 by @Miserlou. Thanks!
