### ISSUE TITLE
Add Popularity Endpoint

### ISSUE THREAD

**Issue by Miserlou** [Jamonek/Robinhood#79]
There appears to be a 'instruments/popularity' API endpoint which drives the "Top Movers" page. I'd love to be able to see this programmatically getting summarized market activity!

**Comment by Jamonek** [comment]
I'll inspect the endpoint tonight.

**Comment by jasonleehodges** [comment]
@Jamonek I'd love to help with this issue if you are looking for contributors?

**Comment by Jamonek** [comment]
Great work, @jasonleehodges !
