### ISSUE TITLE
Add options market information

### ISSUE THREAD

**Issue by jasonleehodges** [Jamonek/Robinhood#86]
I was able to grab the following endpoints that I think would be useful to implement. Would be convenient to have [pull request #84](https://github.com/Jamonek/Robinhood/pull/84) merged before I do so. Also, will need to add in the helper endpoint to convert standard tokens to oauth tokens.

- https://api.robinhood.com/options/instruments/?chain_id={chainId}&expiration_dates={comma separated dates YYYY-MM-DD}&state=active&tradability=tradable&type={call || put}

- https://api.robinhood.com/marketdata/options/{optionId}/

**Comment by mstrum** [comment]
Here's the bulk of the options api incase you're interested (feel free to port them here, the more the merrier!): https://github.com/mstrum/robinhood-python/blob/master/robinhood/RobinhoodClient.py#L2219
