### ISSUE TITLE
def instruments returns error

### ISSUE THREAD

**Issue by Goldeneye22** [Jamonek/Robinhood#92]
Error Message: "_MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?_"

This started happening on the 4/4/2018 Commits.

**Comment by jasonleehodges** [comment]
This should be fixed by PR #91 once it gets merged.

**Comment by Goldeneye22** [comment]
Thank you I couldn't figure out how to fix it myself! Do you know if there is a way to extract the watchlist that is stored on the mobile app? Thanks again.

**Comment by jasonleehodges** [comment]
Are you talking about the "for-you" tag? That is mentioned in issue #90 . There seems to be an endpoint for it but it requires special login (probably needs the oauth2 conversion endpoint to switch over your auth token before it can be used).

**Comment by Goldeneye22** [comment]
Not sure. I will look into it, but I think #92 is closed.
