### ISSUE TITLE
How do I check the current value of a stock

### ISSUE THREAD

**Issue by Njreardo** [Jamonek/Robinhood#99]
I'm currently using the Yahoo api with pandas datareader which is becoming an issue because it can't read all of the urls for some reason. I need a foolproof method of getting current stock prices and preferably the opening price of the stock as well so I can move forward with my program.

**Comment by Goldeneye22** [comment]
**Look at the example.py and try it out to see if it gives you all the data you need.**

from Robinhood import Robinhood

#Setup
my_trader = Robinhood()
#login
my_trader.login(username="YOUR_USERNAME", password="YOUR_PASSWORD")

#Get stock information
    #Note: Sometimes more than one instrument may be returned for a given stock symbol
stock_instrument = my_trader.instruments("GEVO")[0]

#Get a stock's quote
my_trader.print_quote("AAPL")

#Prompt for a symbol
my_trader.print_quote()

#Print multiple symbols
my_trader.print_quotes(stocks=["BBRY", "FB", "MSFT"])

#View all data for a given stock ie. Ask price and size, bid price and size, previous close, adjusted previous close, etc.
quote_info = my_trader.quote_data("GEVO")
print(quote_info)

#Place a buy order (uses market bid price)
buy_order = my_trader.place_buy_order(stock_instrument, 1)

#Place a sell order
sell_order = my_trader.place_sell_order(stock_instrument, 1)

**Comment by Njreardo** [comment]
Thank you so much GoldenEye. You just saved me a lot of money with your message! I was wondering what was wrong with my model.

**Comment by Goldeneye22** [comment]
I very rarely am able to help people on GitHub, but I'm glad I pointed you in the right direction.

**Comment by Njreardo** [comment]
Just as a follow up,

This is the object-
`{"ask_price":"1099.8700","ask_size":100,"bid_price":"1098.1100","bid_size":100,"last_trade_price":"1100.2000","last_extended_hours_trade_price":"1098.1000","previous_close":"1098.2600","adjusted_previous_close":"1098.2600","previous_close_date":"2018-05-11","symbol":"GOOG","trading_halted":false,"has_traded":true,"last_trade_price_source":"consolidated","updated_at":"2018-05-14T22:13:52Z","instrument":"https://api.robinhood.com/instruments/943c5009-a0bb-4665-8cf4-a95dab5874e4/"}`

When I place a buy order it is going to buy based on "bid_price" right?

**Comment by Goldeneye22** [comment]
It will go in as a "market" order on Robinhood, which will vary but be will most likely be between the ask and the bid price as long as you execute the trade after recieving the data.

**Comment by Njreardo** [comment]
Ok, so I'm going to base my trading on ask_price then because it seems to be the safest. I was basing it on last_trade_price. Not doing that anymore

**Comment by Njreardo** [comment]
So when I sell a stock should I base it on the last traded price, bid price, or ask price?

**Comment by Goldeneye22** [comment]
Not sure like I said since you are doing market orders you wont get exactly those prices when selling. If you are just using those prices to trigger a sale then probably last traded.

**Comment by Njreardo** [comment]
That's what I was thinking. Thanks again so much for your help Goldeneye. I needed this information desperately without even realizing it.
